name: Build test

on:
  push:
    branches:
      - 'main'
      - 'dev'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Install dependencies
        uses: ./.github/workflows/install-pnpm

      - name: Build app
        run: |
          pnpm build
          pnpm postbuild
