name: Deploy spektr to bucket

on:
  push:
    branches:
      - dev

env:
  S3_BUCKET: s3://spektr-web-dev

jobs:
  deploy-to-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Install dependencies
        uses: ./.github/workflows/install-pnpm

      - name: Build app
        run: |
          pnpm build
          pnpm postbuild

      - name: 🤌 Upload to s3
        uses: ./.github/workflows/upload-to-s3
        with:
          s3_region: pl-waw
          s3_access_key: ${{ secrets.S3_ACCESS_KEY }}
          s3_secret_key: ${{ secrets.S3_SECRET_KEY }}
          s3_bucket: ${{ env.S3_BUCKET }}
          source: "release/build"
